package com.example.kmmsample.shared.utils

//Error response codes
val REDIRECT_RESPONSE_EXCEPTION_RANGE = 300..399
val CLIENT_REQUEST_EXCEPTION_RANGE = 400..499
val SERVER_RESPONSE_EXCEPTION_RANGE = 500..599
const val RESPONSE_EXCEPTION_CODE = 600
const val UNAUTHORIZED_RESPONSE_CODE = 401